require("impatient") -- for improving load time

require("core.options")
require("core.keymaps")
require("plugins-setup")
require("core.colorscheme")
require("plugins.comment")
require("plugins.nvim-tree")
require("plugins.lualine")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.lsp.mason")
require("plugins.lsp.lspsaga")
require("plugins.lsp.lspconfig")
require("plugins.lsp.null-ls")
require("plugins.autopairs")
require("plugins.treesitter")
require("plugins.nvim-colorizer")
require("plugins.tailwindconfig")
require("plugins.which-key")
require("plugins.scrollbar")
require("plugins.indentlines")
